/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppDashboardRouteImport } from './routes/_app/dashboard'
import { Route as AppAuditIndexRouteImport } from './routes/_app/audit/index'
import { Route as AppEncodingIndexRouteImport } from './routes/_app/encoding/index'
import { Route as AppEncodingConnectorsRouteImport } from './routes/_app/encoding/connectors'
import { Route as AppEncodingSourcesRouteImport } from './routes/_app/encoding/sources'
import { Route as AppOperationsIndexRouteImport } from './routes/_app/operations/index'
import { Route as AppPoliciesIndexRouteImport } from './routes/_app/policies/index'
import { Route as AppRuntimesIndexRouteImport } from './routes/_app/runtimes/index'
import { Route as AppRuntimesIdRouteImport } from './routes/_app/runtimes/$id'
import { Route as AppRuntimesRegisterRouteImport } from './routes/_app/runtimes/register'
import { Route as AppSettingsOrganizationRouteImport } from './routes/_app/settings/organization'
import { Route as AppSimulationsIndexRouteImport } from './routes/_app/simulations/index'
import { Route as AppWorkQueueIndexRouteImport } from './routes/_app/work-queue/index'
import { Route as AppWorkQueueIdRouteImport } from './routes/_app/work-queue/$id'
import { Route as AppEncodingIrIdRouteImport } from './routes/_app/encoding/ir/$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppAuditIndexRoute = AppAuditIndexRouteImport.update({
  id: '/audit/',
  path: '/audit/',
  getParentRoute: () => AppRoute,
} as any)
const AppEncodingIndexRoute = AppEncodingIndexRouteImport.update({
  id: '/encoding/',
  path: '/encoding/',
  getParentRoute: () => AppRoute,
} as any)
const AppEncodingConnectorsRoute = AppEncodingConnectorsRouteImport.update({
  id: '/encoding/connectors',
  path: '/encoding/connectors',
  getParentRoute: () => AppRoute,
} as any)
const AppEncodingSourcesRoute = AppEncodingSourcesRouteImport.update({
  id: '/encoding/sources',
  path: '/encoding/sources',
  getParentRoute: () => AppRoute,
} as any)
const AppOperationsIndexRoute = AppOperationsIndexRouteImport.update({
  id: '/operations/',
  path: '/operations/',
  getParentRoute: () => AppRoute,
} as any)
const AppPoliciesIndexRoute = AppPoliciesIndexRouteImport.update({
  id: '/policies/',
  path: '/policies/',
  getParentRoute: () => AppRoute,
} as any)
const AppRuntimesIndexRoute = AppRuntimesIndexRouteImport.update({
  id: '/runtimes/',
  path: '/runtimes/',
  getParentRoute: () => AppRoute,
} as any)
const AppRuntimesIdRoute = AppRuntimesIdRouteImport.update({
  id: '/runtimes/$id',
  path: '/runtimes/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppRuntimesRegisterRoute = AppRuntimesRegisterRouteImport.update({
  id: '/runtimes/register',
  path: '/runtimes/register',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsOrganizationRoute = AppSettingsOrganizationRouteImport.update({
  id: '/settings/organization',
  path: '/settings/organization',
  getParentRoute: () => AppRoute,
} as any)
const AppSimulationsIndexRoute = AppSimulationsIndexRouteImport.update({
  id: '/simulations/',
  path: '/simulations/',
  getParentRoute: () => AppRoute,
} as any)
const AppWorkQueueIndexRoute = AppWorkQueueIndexRouteImport.update({
  id: '/work-queue/',
  path: '/work-queue/',
  getParentRoute: () => AppRoute,
} as any)
const AppWorkQueueIdRoute = AppWorkQueueIdRouteImport.update({
  id: '/work-queue/$id',
  path: '/work-queue/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppEncodingIrIdRoute = AppEncodingIrIdRouteImport.update({
  id: '/encoding/ir/$id',
  path: '/encoding/ir/$id',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof AppDashboardRoute
  '/encoding/connectors': typeof AppEncodingConnectorsRoute
  '/encoding/sources': typeof AppEncodingSourcesRoute
  '/runtimes/$id': typeof AppRuntimesIdRoute
  '/runtimes/register': typeof AppRuntimesRegisterRoute
  '/settings/organization': typeof AppSettingsOrganizationRoute
  '/work-queue/$id': typeof AppWorkQueueIdRoute
  '/audit/': typeof AppAuditIndexRoute
  '/encoding/': typeof AppEncodingIndexRoute
  '/operations/': typeof AppOperationsIndexRoute
  '/policies/': typeof AppPoliciesIndexRoute
  '/runtimes/': typeof AppRuntimesIndexRoute
  '/simulations/': typeof AppSimulationsIndexRoute
  '/work-queue/': typeof AppWorkQueueIndexRoute
  '/encoding/ir/$id': typeof AppEncodingIrIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof AppDashboardRoute
  '/encoding/connectors': typeof AppEncodingConnectorsRoute
  '/encoding/sources': typeof AppEncodingSourcesRoute
  '/runtimes/$id': typeof AppRuntimesIdRoute
  '/runtimes/register': typeof AppRuntimesRegisterRoute
  '/settings/organization': typeof AppSettingsOrganizationRoute
  '/work-queue/$id': typeof AppWorkQueueIdRoute
  '/audit': typeof AppAuditIndexRoute
  '/encoding': typeof AppEncodingIndexRoute
  '/operations': typeof AppOperationsIndexRoute
  '/policies': typeof AppPoliciesIndexRoute
  '/runtimes': typeof AppRuntimesIndexRoute
  '/simulations': typeof AppSimulationsIndexRoute
  '/work-queue': typeof AppWorkQueueIndexRoute
  '/encoding/ir/$id': typeof AppEncodingIrIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/encoding/connectors': typeof AppEncodingConnectorsRoute
  '/_app/encoding/sources': typeof AppEncodingSourcesRoute
  '/_app/runtimes/$id': typeof AppRuntimesIdRoute
  '/_app/runtimes/register': typeof AppRuntimesRegisterRoute
  '/_app/settings/organization': typeof AppSettingsOrganizationRoute
  '/_app/work-queue/$id': typeof AppWorkQueueIdRoute
  '/_app/audit/': typeof AppAuditIndexRoute
  '/_app/encoding/': typeof AppEncodingIndexRoute
  '/_app/operations/': typeof AppOperationsIndexRoute
  '/_app/policies/': typeof AppPoliciesIndexRoute
  '/_app/runtimes/': typeof AppRuntimesIndexRoute
  '/_app/simulations/': typeof AppSimulationsIndexRoute
  '/_app/work-queue/': typeof AppWorkQueueIndexRoute
  '/_app/encoding/ir/$id': typeof AppEncodingIrIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/encoding/connectors'
    | '/encoding/sources'
    | '/runtimes/$id'
    | '/runtimes/register'
    | '/settings/organization'
    | '/work-queue/$id'
    | '/audit/'
    | '/encoding/'
    | '/operations/'
    | '/policies/'
    | '/runtimes/'
    | '/simulations/'
    | '/work-queue/'
    | '/encoding/ir/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/encoding/connectors'
    | '/encoding/sources'
    | '/runtimes/$id'
    | '/runtimes/register'
    | '/settings/organization'
    | '/work-queue/$id'
    | '/audit'
    | '/encoding'
    | '/operations'
    | '/policies'
    | '/runtimes'
    | '/simulations'
    | '/work-queue'
    | '/encoding/ir/$id'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/_app/dashboard'
    | '/_app/encoding/connectors'
    | '/_app/encoding/sources'
    | '/_app/runtimes/$id'
    | '/_app/runtimes/register'
    | '/_app/settings/organization'
    | '/_app/work-queue/$id'
    | '/_app/audit/'
    | '/_app/encoding/'
    | '/_app/operations/'
    | '/_app/policies/'
    | '/_app/runtimes/'
    | '/_app/simulations/'
    | '/_app/work-queue/'
    | '/_app/encoding/ir/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/audit/': {
      id: '/_app/audit/'
      path: '/audit'
      fullPath: '/audit/'
      preLoaderRoute: typeof AppAuditIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/encoding/': {
      id: '/_app/encoding/'
      path: '/encoding'
      fullPath: '/encoding/'
      preLoaderRoute: typeof AppEncodingIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/encoding/connectors': {
      id: '/_app/encoding/connectors'
      path: '/encoding/connectors'
      fullPath: '/encoding/connectors'
      preLoaderRoute: typeof AppEncodingConnectorsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/encoding/sources': {
      id: '/_app/encoding/sources'
      path: '/encoding/sources'
      fullPath: '/encoding/sources'
      preLoaderRoute: typeof AppEncodingSourcesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/operations/': {
      id: '/_app/operations/'
      path: '/operations'
      fullPath: '/operations/'
      preLoaderRoute: typeof AppOperationsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/policies/': {
      id: '/_app/policies/'
      path: '/policies'
      fullPath: '/policies/'
      preLoaderRoute: typeof AppPoliciesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/runtimes/': {
      id: '/_app/runtimes/'
      path: '/runtimes'
      fullPath: '/runtimes/'
      preLoaderRoute: typeof AppRuntimesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/runtimes/$id': {
      id: '/_app/runtimes/$id'
      path: '/runtimes/$id'
      fullPath: '/runtimes/$id'
      preLoaderRoute: typeof AppRuntimesIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/runtimes/register': {
      id: '/_app/runtimes/register'
      path: '/runtimes/register'
      fullPath: '/runtimes/register'
      preLoaderRoute: typeof AppRuntimesRegisterRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings/organization': {
      id: '/_app/settings/organization'
      path: '/settings/organization'
      fullPath: '/settings/organization'
      preLoaderRoute: typeof AppSettingsOrganizationRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/simulations/': {
      id: '/_app/simulations/'
      path: '/simulations'
      fullPath: '/simulations/'
      preLoaderRoute: typeof AppSimulationsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/work-queue/': {
      id: '/_app/work-queue/'
      path: '/work-queue'
      fullPath: '/work-queue/'
      preLoaderRoute: typeof AppWorkQueueIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/work-queue/$id': {
      id: '/_app/work-queue/$id'
      path: '/work-queue/$id'
      fullPath: '/work-queue/$id'
      preLoaderRoute: typeof AppWorkQueueIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/encoding/ir/$id': {
      id: '/_app/encoding/ir/$id'
      path: '/encoding/ir/$id'
      fullPath: '/encoding/ir/$id'
      preLoaderRoute: typeof AppEncodingIrIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppDashboardRoute: typeof AppDashboardRoute
  AppEncodingConnectorsRoute: typeof AppEncodingConnectorsRoute
  AppEncodingSourcesRoute: typeof AppEncodingSourcesRoute
  AppRuntimesIdRoute: typeof AppRuntimesIdRoute
  AppRuntimesRegisterRoute: typeof AppRuntimesRegisterRoute
  AppSettingsOrganizationRoute: typeof AppSettingsOrganizationRoute
  AppWorkQueueIdRoute: typeof AppWorkQueueIdRoute
  AppAuditIndexRoute: typeof AppAuditIndexRoute
  AppEncodingIndexRoute: typeof AppEncodingIndexRoute
  AppOperationsIndexRoute: typeof AppOperationsIndexRoute
  AppPoliciesIndexRoute: typeof AppPoliciesIndexRoute
  AppRuntimesIndexRoute: typeof AppRuntimesIndexRoute
  AppSimulationsIndexRoute: typeof AppSimulationsIndexRoute
  AppWorkQueueIndexRoute: typeof AppWorkQueueIndexRoute
  AppEncodingIrIdRoute: typeof AppEncodingIrIdRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppDashboardRoute: AppDashboardRoute,
  AppEncodingConnectorsRoute: AppEncodingConnectorsRoute,
  AppEncodingSourcesRoute: AppEncodingSourcesRoute,
  AppRuntimesIdRoute: AppRuntimesIdRoute,
  AppRuntimesRegisterRoute: AppRuntimesRegisterRoute,
  AppSettingsOrganizationRoute: AppSettingsOrganizationRoute,
  AppWorkQueueIdRoute: AppWorkQueueIdRoute,
  AppAuditIndexRoute: AppAuditIndexRoute,
  AppEncodingIndexRoute: AppEncodingIndexRoute,
  AppOperationsIndexRoute: AppOperationsIndexRoute,
  AppPoliciesIndexRoute: AppPoliciesIndexRoute,
  AppRuntimesIndexRoute: AppRuntimesIndexRoute,
  AppSimulationsIndexRoute: AppSimulationsIndexRoute,
  AppWorkQueueIndexRoute: AppWorkQueueIndexRoute,
  AppEncodingIrIdRoute: AppEncodingIrIdRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
